# Generated by Django 5.0 on 2025-03-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_detection_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firealert',
            name='annotated_image',
            field=models.ImageField(blank=True, null=True, upload_to='alerts/'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='vote',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
