# Generated by Django 5.0 on 2025-03-22 03:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_detection_app', '0002_firealert_annotated_image_alter_verification_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='firealert',
            name='fire_size',
            field=models.CharField(blank=True, choices=[('small', 'Small Fire'), ('medium', 'Medium Fire'), ('large', 'Large Fire')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='firealert',
            name='verification_deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='correct_verifications',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_verification',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rank',
            field=models.CharField(choices=[('rookie', 'Rookie Guardian'), ('trusted', 'Trusted Guardian'), ('expert', 'Expert Guardian'), ('master', 'Master Guardian'), ('legend', 'Legendary Guardian')], default='rookie', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='response_time_avg',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='verification',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verification',
            name='notification_sent',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='points_awarded',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verification',
            name='response_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='firealert',
            name='detection_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='firealert',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('confirmed', 'Fire Confirmed'), ('false_alarm', 'False Alarm')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='firealert',
            name='weather_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='vote',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='firealert',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fire_detection_app.camera'),
        ),
    ]
